version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.31
    container_name: mysqldb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysqldb_volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  learning-courses:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysqldb_volume: