version: '3'
services:
  learning-courses:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning-courses
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - learning-courses-net

  mysqldb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysqldb
    ports:
      - "33099:3306"
    environment:
      - MYSQL_DATABASE=courses
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - learning-courses-net

networks:
  learning-courses-net: